on: 
  push:
    branches: [main]
  pull_request:


jobs:
  makelib_job:
    runs-on: ubuntu-latest
    name: Make library job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: 
          go-version: '>=1.18.0'

      - name: Setup JDK step 
        uses: actions/setup-java@v3
        with: 
          java-version: 11
          distribution: 'zulu'

      - name: Setup Android SDK step 
        uses: android-actions/setup-android@v2

      - name: Add gomobile step 
        run: |
          go install github.com/hajimehoshi/ebiten/v2/cmd/ebitenmobile@latest
          go get golang.org/x/mobile/bind
          ebitenmobile bind -target android -javapkg io.itch.shrmpy.egj2022 -o ./mobile/android/egjlib/egjlib.aar ./mobile

      - name: Archive lib artifacts 
        uses: actions/upload-artifact@v3
        with: 
          name: ebitenmobile-view-lib
          retention-days: 1
          path: |
            mobile/android/egjlib/*.aar

