on: 
  push:
    branches: [main]
  pull_request:


jobs:
  makelib_job:
    runs-on: ubuntu-latest
    name: Make library job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: 
          go-version: '>=1.18.0'

      - name: Setup JDK step 
        uses: actions/setup-java@v3
        with: 
          java-version: 11
          distribution: 'zulu'

      - name: Setup Android SDK step 
        uses: android-actions/setup-android@v2

      - name: Add gomobile step 
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init
          go get golang.org/x/mobile/bind
          gomobile bind --target android

      - name: Archive lib artifacts 
        uses: actions/upload-artifact@v3
        with: 
          name: and-shared-lib
          path: |
            *.aar

